### ISSUE TITLE
Wahl der DB

### ISSUE THREAD

**Issue by rogerzaugg** [bbzblit/m426-api#2]
Überlegt euch nochmal die Wahl der passenden Datenbank. Bei Eurem Usecase würde ich auf eine relationale Datenbank setzen. Die Daten sind strukturiert, die zu erstellenden Analysen für die Statistiken sind ebenfalls klar, gewisse Usecases bieten Potenzial für ein Transaction Handling.

**Comment by Yanni8** [comment]
Wir haben uns in der Gruppe dafür entschieden MariaDB zu verwenden!
